# Generated by Django 2.1.7 on 2021-06-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('item_qty', models.IntegerField()),
                ('item_status', models.TextField()),
                ('item_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='gitem',
            name='glist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gList.GList'),
        ),
    ]
