# Generated by Django 2.1.7 on 2021-06-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitem',
            name='glist',
        ),
        migrations.DeleteModel(
            name='GList',
        ),
    ]
